name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # This triggers the script every time you push to main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Web
        run: flutter config --enable-web

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Web App
        # Replace 'SatNotesApp' with your exact repo name if different
        run: flutter build web --release --base-href "/SatNotesApp/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
 